/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-04-27 14:46:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class board01_005fmy_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>");
      out.print(request.getServletPath());
      out.write("</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/cupertino/jquery-ui.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("\tfont-size: 70%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#accordion>div>div:last-child {\r\n");
      out.write("\ttext-align: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#accordion-resizer {\r\n");
      out.write("\tmargin: 0 60px;\r\n");
      out.write("\tmax-width: 1500px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#btngroup {\r\n");
      out.write("\ttext-align: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#btngroup button {\r\n");
      out.write("\tmargin: 3px;\r\n");
      out.write("\tpadding: 3px;\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label.header {\r\n");
      out.write("\tfont-size: 10pt;\r\n");
      out.write("\tmargin-right: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input.text {\r\n");
      out.write("\twidth: 80%;\r\n");
      out.write("\tmargin-bottom: 12px;\r\n");
      out.write("\tpadding: 0.4em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("fieldset {\r\n");
      out.write("\tmargin-left: 15px;\r\n");
      out.write("\tmargin-top: 15px;\r\n");
      out.write("\tborder: 0;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/jquery-3.4.1.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/jquery-ui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$('#writeDialog').css('display', 'none');\r\n");
      out.write("\t\t$('#modifyDialog').css('display', 'none');\r\n");
      out.write("\t\t$('#deleteDialog').css('display', 'none');\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t$('#accordion').accordion({\r\n");
      out.write("\t\t\tcollapsible : 'true',\r\n");
      out.write("\t\t\theightStyle : 'content'\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$('button.action').button();\r\n");
      out.write("\r\n");
      out.write("\t\t/* \r\n");
      out.write("\t\tvar readServer = function() {\r\n");
      out.write("\t\t\t$('#accordion').accordion({\r\n");
      out.write("\t\t\t\tcollapsible : 'true',\r\n");
      out.write("\t\t\t\theightStyle : 'content'\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$('button .action').button();\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t */\r\n");
      out.write("\r\n");
      out.write("\t\treadServer();\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t$(document).on('click', 'button.action', function() {\r\n");
      out.write("\t\t\tif ($(this).attr('action') == 'write') {\r\n");
      out.write("\t\t\t\t$('#writeDialog').dialog({\r\n");
      out.write("\t\t\t\t\twidth : 700,\r\n");
      out.write("\t\t\t\t\theight : 500,\r\n");
      out.write("\t\t\t\t\tmodal : true,\r\n");
      out.write("\t\t\t\t\tbuttons : {\r\n");
      out.write("\t\t\t\t\t\t'글쓰기' : function() {\r\n");
      out.write("\t\t\t\t\t\t\twriteServer();\r\n");
      out.write("\t\t\t\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t'취소' : function() {\r\n");
      out.write("\t\t\t\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tclose : function() {\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tvar readServer = function() {\t\t\r\n");
      out.write("\t\t//$('#accordion').empty();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t// 다국어이면 url 인코딩\r\n");
      out.write("\t\t\turl : './list.json',\t\t\t\t\t\r\n");
      out.write("\t\t\ttype : 'get',\r\n");
      out.write("\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\tsuccess : function(data) {\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#accordion').empty();\r\n");
      out.write("\t\t\t\tconsole.log(\"성공\");\r\n");
      out.write("\t\t\t\t$.each(data.data, function(i, element) {\r\n");
      out.write("\t\t\t\t\tvar html = \"\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t//js객체이기때문에 직접접근. jsonajax01 참고\r\n");
      out.write("\t\t\t\t\t//console.log(element);\r\n");
      out.write("\t\t\t\t\t//console.log(element.subject);\r\n");
      out.write("\t\t\t\t\t//console.log($(element).find(\"seq\").val());\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t/*\r\n");
      out.write("\t\t\t\t\t<h3>1 : 글쓴이(0) new</h3>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<div>2016-02-01</div>\r\n");
      out.write("\t\t\t\t\t\t<div>제목 1</div>\r\n");
      out.write("\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t<hr noshade=\"noshade\" />\r\n");
      out.write("\t\t\t\t\t\t<div>내용 1</div>\r\n");
      out.write("\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t<hr noshade=\"noshade\" />\r\n");
      out.write("\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<button idx=\"1\" action=\"modify\" class=\"action\">수정</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button idx=\"1\" action=\"delete\" class=\"action\">삭제</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t       \r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t*/\r\n");
      out.write("\t\t\t\t\thtml += \"<h3>\" + element.seq + \" : \" + element.writer + \"</h3>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<div>\";\r\n");
      out.write("\t\t\t\t\thtml += \"\t<div>\"+ element.wdate +  \"</div>\";\r\n");
      out.write("\t\t\t\t\thtml += \"\t<div>\" + element.subject +\"</div>\";\r\n");
      out.write("\t\t\t\t\thtml += \"\t<br />\";\r\n");
      out.write("\t\t\t\t\thtml += \"\t<hr noshade='noshade' />\";\r\n");
      out.write("\t\t\t\t\thtml += \"\t<div>\" + element.content +\"</div>\";\r\n");
      out.write("\t\t\t\t\thtml += \"\t<br />\";\r\n");
      out.write("\t\t\t\t\thtml += \"\t<hr noshade='noshade' />\";\r\n");
      out.write("\t\t\t\t\thtml += \"\t<br />\";\r\n");
      out.write("\t\t\t\t\thtml += \"\t<div>\";\r\n");
      out.write("\t\t\t\t\thtml += \"\t\t<button id='mod\"+ i +\"' action='modify' class='action'>수정</button>\";\r\n");
      out.write("\t\t\t\t\thtml += \"\t\t<button id='del\"+ i +\"' action='delete' class='action'>삭제</button>\";\r\n");
      out.write("\t\t\t\t\thtml += \"\t</div>\";\r\n");
      out.write("\t\t\t\t\thtml += \"</div>\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#accordion\" ).append(html);\r\n");
      out.write("\t\t\t\t\t$('#mod' + i ).button().on('click', function(e) {\r\n");
      out.write("\t\t\t\t\t\tshowModyfiDialog(element.seq);\t\t\t\t\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$('#del' + i ).button().on('click', function(e) {\r\n");
      out.write("\t\t\t\t\t\tshowDeleteDialog(element.seq);\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t$(\"#accordion\").accordion('refresh');\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(error) {\r\n");
      out.write("\t\t\t\t// 404일때\r\n");
      out.write("\t\t\t\tconsole.log('실패 : ' + error.status);\r\n");
      out.write("\t\t\t\tconsole.log(error.responseText);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tvar writeServer = function() {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t// 다국어이면 url 인코딩\r\n");
      out.write("\t\t\turl : './write_ok.json',\r\n");
      out.write("\t\t\tdata: {\r\n");
      out.write("\t\t\t\tsubject : $('#w_subject').val(),\r\n");
      out.write("\t\t\t\twriter : $('#w_writer').val(),\r\n");
      out.write("\t\t\t\tmail : $('#w_mail').val(),\r\n");
      out.write("\t\t\t\tpassword : $('#w_password').val(),\r\n");
      out.write("\t\t\t\tcontent : $('#w_content').val(),\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\ttype : 'get',\r\n");
      out.write("\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\tsuccess : function(json) {\t\t\t\t\r\n");
      out.write("\t\t\t\t//return json.flag;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(json.flag == 0) {\r\n");
      out.write("\t\t\t\t\talert('글쓰기에 성공했습니다.');\r\n");
      out.write("\t\t\t\t\treadServer();\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\talert('글쓰기에 실패했습니다.');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(error) {\r\n");
      out.write("\t\t\t\t// 404일때\r\n");
      out.write("\t\t\t\tconsole.log('실패 : ' + error.status);\r\n");
      out.write("\t\t\t\tconsole.log(error.responseText);\r\n");
      out.write("\t\t\t\treturn 1;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar showModyfiDialog = function(seq) {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t// 다국어이면 url 인코딩\r\n");
      out.write("\t\t\turl : './modify.json',\r\n");
      out.write("\t\t\tdata: {\r\n");
      out.write("\t\t\t\tseq : seq\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\ttype : 'get',\r\n");
      out.write("\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\tsuccess : function(json) {\t\t\t\t\r\n");
      out.write("\t\t\t\t//return json.flag;\t\t\t\t\t\r\n");
      out.write("\t\t\t\tif(json.flag == 0){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar data = json.data;\r\n");
      out.write("\t\t\t\t\t//console.log(data.subject);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$('#m_subject').val(data.subject);\r\n");
      out.write("\t\t\t\t\t$('#m_writer').val(data.writer);\r\n");
      out.write("\t\t\t\t\t$('#m_mail').val(data.mail);\r\n");
      out.write("\t\t\t\t\t$('#m_content').val(data.content);\r\n");
      out.write("\t\t\t\t\t$('#m_password').val('');\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t$('#modifyDialog').dialog({\r\n");
      out.write("\t\t\t\t\t\twidth : 700,\r\n");
      out.write("\t\t\t\t\t\theight : 500,\r\n");
      out.write("\t\t\t\t\t\tmodal : true,\r\n");
      out.write("\t\t\t\t\t\tbuttons : {\r\n");
      out.write("\t\t\t\t\t\t\t'수정' : function() {\r\n");
      out.write("\t\t\t\t\t\t\t\tmodServer(seq);\r\n");
      out.write("\t\t\t\t\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t'취소' : function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\tclose : function() {\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\talert('error');\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(error) {\r\n");
      out.write("\t\t\t\t// 404일때\r\n");
      out.write("\t\t\t\tconsole.log('실패 : ' + error.status);\r\n");
      out.write("\t\t\t\tconsole.log(error.responseText);\r\n");
      out.write("\t\t\t\treturn 1;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar modServer = function(seq) {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t// 다국어이면 url 인코딩\r\n");
      out.write("\t\t\turl : './modify_ok.json',\r\n");
      out.write("\t\t\tdata: {\r\n");
      out.write("\t\t\t\tseq : seq,\r\n");
      out.write("\t\t\t\tpassword : $('#m_password').val(),\r\n");
      out.write("\t\t\t\tsubject : $('#m_subject').val(),\r\n");
      out.write("\t\t\t\tmail : $('#m_mail').val(),\r\n");
      out.write("\t\t\t\tcontent : $('#m_content').val(),\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\ttype : 'get',\r\n");
      out.write("\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\tsuccess : function(json) {\t\t\t\t\r\n");
      out.write("\t\t\t\t//return json.flag;\r\n");
      out.write("\t\t\t\tif(json.flag == 0) {\r\n");
      out.write("\t\t\t\t\talert('글수정에 성공했습니다.');\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\treadServer();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t} else if(json.flag == 1) {\r\n");
      out.write("\t\t\t\t\talert('비밀번호가 틀립니다.');\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\talert('글수정에 실패했습니다.');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(error) {\r\n");
      out.write("\t\t\t\t// 404일때\r\n");
      out.write("\t\t\t\tconsole.log('실패 : ' + error.status);\r\n");
      out.write("\t\t\t\tconsole.log(error.responseText);\r\n");
      out.write("\t\t\t\treturn 1;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar showDeleteDialog = function(seq) {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t// 다국어이면 url 인코딩\r\n");
      out.write("\t\t\turl : './delete.json',\r\n");
      out.write("\t\t\tdata: {\r\n");
      out.write("\t\t\t\tseq : seq\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\ttype : 'get',\r\n");
      out.write("\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\tsuccess : function(json) {\t\t\t\t\r\n");
      out.write("\t\t\t\t//return json.flag;\t\t\t\t\t\r\n");
      out.write("\t\t\t\tif(json.flag == 0){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar data = json.data;\r\n");
      out.write("\t\t\t\t\t//console.log(data.subject);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$('#d_subject').val(data.subject);\r\n");
      out.write("\t\t\t\t\t$('#d_password').val('');\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$('#deleteDialog').dialog({\r\n");
      out.write("\t\t\t\t\t\twidth : 700,\r\n");
      out.write("\t\t\t\t\t\theight : 200,\r\n");
      out.write("\t\t\t\t\t\tmodal : true,\r\n");
      out.write("\t\t\t\t\t\tbuttons : {\r\n");
      out.write("\t\t\t\t\t\t\t'삭제' : function() {\r\n");
      out.write("\t\t\t\t\t\t\t\tdelServer(seq);\r\n");
      out.write("\t\t\t\t\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t'취소' : function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\tclose : function() {\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\talert('error');\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(error) {\r\n");
      out.write("\t\t\t\t// 404일때\r\n");
      out.write("\t\t\t\tconsole.log('실패 : ' + error.status);\r\n");
      out.write("\t\t\t\tconsole.log(error.responseText);\r\n");
      out.write("\t\t\t\treturn 1;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\tvar delServer = function(seq) {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t// 다국어이면 url 인코딩\r\n");
      out.write("\t\t\turl : './delete_ok.json',\r\n");
      out.write("\t\t\tdata: {\r\n");
      out.write("\t\t\t\tseq : seq,\r\n");
      out.write("\t\t\t\tpassword : $('#d_password').val(),\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\ttype : 'get',\r\n");
      out.write("\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\tsuccess : function(json) {\t\t\t\t\r\n");
      out.write("\t\t\t\t//return json.flag;\r\n");
      out.write("\t\t\t\tif(json.flag == 0) {\r\n");
      out.write("\t\t\t\t\talert('글삭제에 성공했습니다.');\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\treadServer();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t} else if(json.flag == 1) {\r\n");
      out.write("\t\t\t\t\talert('비밀번호 틀립니다.');\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\talert('글삭제에 실패했습니다.');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(error) {\r\n");
      out.write("\t\t\t\t// 404일때\r\n");
      out.write("\t\t\t\tconsole.log('실패 : ' + error.status);\r\n");
      out.write("\t\t\t\tconsole.log(error.responseText);\r\n");
      out.write("\t\t\t\treturn 1;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"accordion-resizer\">\r\n");
      out.write("\t\t<hr noshade=\"noshade\" />\r\n");
      out.write("\t\t<div id=\"accordion\">\r\n");
      out.write("\t\t\t<h3>1 : 글쓴이(0) new</h3>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<div>2016-02-01</div>\r\n");
      out.write("\t\t\t\t<div>제목 1</div>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<hr noshade=\"noshade\" />\r\n");
      out.write("\t\t\t\t<div>내용 1</div>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<hr noshade=\"noshade\" />\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<button idx=\"1\" action=\"modify\" class=\"action\">수정</button>\r\n");
      out.write("\t\t\t\t\t<button idx=\"1\" action=\"delete\" class=\"action\">삭제</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t       \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<h3>2 : 글쓴이(0) new</h3>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<div>2016-02-01</div>\r\n");
      out.write("\t\t\t\t<div>제목 2</div>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<hr noshade=\"noshade\" />\r\n");
      out.write("\t\t\t\t<div>내용 2</div>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<hr noshade=\"noshade\" />\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<button idx=\"2\" action=\"modify\" class=\"action\">수정</button>\r\n");
      out.write("\t\t\t\t\t<button idx=\"2\" action=\"delete\" class=\"action\">삭제</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t       \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<hr noshade=\"noshade\" />\r\n");
      out.write("\t\t<div id=\"btngroup\">\r\n");
      out.write("\t\t\t<button action=\"write\" class=\"action\">글쓰기</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"writeDialog\" title=\"글쓰기\">\r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label for=\"subject\" class=\"header\">제&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;목</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"w_subject\"\r\n");
      out.write("\t\t\t\t\tclass=\"text ui-widget-content ui-corner-all\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label for=\"writer\" class=\"header\">이&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;름</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"w_writer\"\r\n");
      out.write("\t\t\t\t\tclass=\"text ui-widget-content ui-corner-all\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label for=\"mail\" class=\"header\">메&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;일</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"w_mail\"\r\n");
      out.write("\t\t\t\t\tclass=\"text ui-widget-content ui-corner-all\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label for=\"password\" class=\"header\">비밀&nbsp;번호</label> <input\r\n");
      out.write("\t\t\t\t\ttype=\"password\" id=\"w_password\"\r\n");
      out.write("\t\t\t\t\tclass=\"text ui-widget-content ui-corner-all\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label for=\"content\" class=\"header\">본&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;문</label>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<textarea rows=\"15\" cols=\"100\" id=\"w_content\"\r\n");
      out.write("\t\t\t\t\tclass=\"text ui-widget-content ui-corner-all\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"modifyDialog\" title=\"글수정\">\r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label for=\"subject\" class=\"header\">제&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;목</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"m_subject\"\r\n");
      out.write("\t\t\t\t\tclass=\"text ui-widget-content ui-corner-all\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label for=\"writer\" class=\"header\">이&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;름</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"m_writer\"\r\n");
      out.write("\t\t\t\t\tclass=\"text ui-widget-content ui-corner-all\" readonly=\"readonly\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label for=\"mail\" class=\"header\">메&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;일</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"m_mail\"\r\n");
      out.write("\t\t\t\t\tclass=\"text ui-widget-content ui-corner-all\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label for=\"password\" class=\"header\">비밀&nbsp;번호</label> <input\r\n");
      out.write("\t\t\t\t\ttype=\"password\" id=\"m_password\"\r\n");
      out.write("\t\t\t\t\tclass=\"text ui-widget-content ui-corner-all\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label for=\"content\" class=\"header\">본&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;문</label>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<textarea rows=\"15\" cols=\"100\" id=\"m_content\"\r\n");
      out.write("\t\t\t\t\tclass=\"text ui-widget-content ui-corner-all\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"deleteDialog\" title=\"글삭제\">\r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label for=\"subject\" class=\"header\">제&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;목</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"d_subject\"\r\n");
      out.write("\t\t\t\t\tclass=\"text ui-widget-content ui-corner-all\" readonly=\"readonly\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<label for=\"password\" class=\"header\">비밀&nbsp;번호</label> <input\r\n");
      out.write("\t\t\t\t\ttype=\"password\" id=\"d_password\"\r\n");
      out.write("\t\t\t\t\tclass=\"text ui-widget-content ui-corner-all\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
